[project]
name = 'Freelance-Dispute-Resolution-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.escrow-contract]
path = 'contracts/escrow-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.job-contract]
path = 'contracts/job-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
